# Generated by Django 5.2.4 on 2025-09-01 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("bird", "Bird"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=100)),
                ("sex", models.CharField(blank=True, max_length=10)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="pet_photos/"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
