# Generated by Django 5.2.6 on 2025-09-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_options_remove_pet_sex_pet_age_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age_years',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
