# Generated by Django 5.2.12 on 2026-04-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_allergy_dietplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('Fish', 'fish'), ('Hen', 'Hen'), ('Cow', 'Cow'), ('other', 'Other')], default='dog', max_length=10),
        ),
    ]
