# Generated by Django 5.2.12 on 2026-04-14 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='food_type',
            field=models.CharField(choices=[('Dry', 'Dry Food'), ('Wet', 'Wet Food'), ('Homemade', 'Homemade'), ('Raw', 'Raw Food'), ('Treats', 'Treats'), ('Other', 'Other')], default='Dry', max_length=50),
        ),
        migrations.AddField(
            model_name='dietplan',
            name='meal_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of the meal'),
        ),
    ]
