# Generated by Django 5.2.12 on 2026-04-14 07:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_dietplan_food_type_dietplan_meal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('Happy', 'Happy 😄'), ('Calm', 'Calm 🙂'), ('Anxious', 'Anxious 😟'), ('Aggressive', 'Aggressive 😠'), ('Low_Energetic', 'Low/Energetic 😴⚡')], max_length=50)),
                ('log_date', models.DateField(default=django.utils.timezone.now, help_text='Date of the mood')),
                ('notes', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_logs', to='pets.pet')),
            ],
        ),
    ]
