# Generated by Django 5.2.12 on 2026-04-14 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_moodlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('Normal', 'Normal Consultation'), ('Emergency', 'Emergency 🚨')], default='Normal', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending Connection'), ('Active', 'Active Consultation'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('doctor_notes', models.TextField(blank=True, help_text='Notes provided by the vet after consult', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_consultations', to='pets.pet')),
            ],
        ),
    ]
