# Generated by Django 5.2.6 on 2025-09-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('pets', '0005_allergy_dietplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='pet_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='pets.pet'),
        ),
    ]
